;;; ip-tax.el --- Tax tracking and Beancount integration -*- lexical-binding: t; -*-

;; Copyright (C) 2025 IP Management System
;; Author: IP Management System
;; Version: 1.0
;; Keywords: org, tax, accounting, beancount
;; Package-Requires: ((emacs "27.1") (org "9.0"))

;;; Commentary:

;; Tax tracking and ledger management module for IP management system.
;; Provides Beancount integration for freelance income and expense tracking.
;;
;; Features:
;; - Automatic transaction recording from invoices
;; - Manual income/expense entry
;; - Beancount ledger file management
;; - Optional integration with ip-invoice module
;;
;; Usage:
;;   M-x ip-tax-record-income    ; Record income manually
;;   M-x ip-tax-record-expense   ; Record expense manually
;;   M-x ip-tax-show-ledger      ; View ledger file

;;; Code:

(require 'cl-lib)
(require 'subr-x)
(require 'ip-core)

;; External dependencies
(declare-function ip-debug-log "ip-debug" (level module message &rest args))

;; Optional Beancount support
(condition-case nil
    (require 'beancount)
  (error
   (defun ip-tax--beancount-mode-available-p ()
     "Check if beancount-mode is available."
     nil)))

;; Fallback logging if ip-debug is not available
(condition-case nil
    (require 'ip-debug)
  (error
   (defun ip-debug-log (level module message &rest args)
     "Fallback logging function."
     (let ((formatted-msg (apply #'format message args))
           (level-str (pcase level
                        ('info "INFO")
                        ('success "SUCCESS")
                        ('warning "WARNING")
                        ('error "ERROR")
                        (_ "DEBUG")))
           (module-str (upcase (symbol-name module))))
       (message "[%s/%s] %s" module-str level-str formatted-msg)))
   
   (defmacro ip-debug (module message &rest args)
     "Fallback debug macro."
     `(ip-debug-log 'info ,module ,message ,@args))))

;;; Customization

(defgroup ip-tax nil
  "Tax and ledger tracking for IP management system."
  :group 'ip-core
  :prefix "ip-tax-")

(defcustom ip-tax-enabled nil
  "Enable automatic tax and ledger tracking.
When non-nil, transactions are recorded to the Beancount ledger file."
  :type 'boolean
  :group 'ip-tax)

(defcustom ip-tax-ledger-file (expand-file-name "tax.beancount" ip-org-directory)
  "Path to Beancount ledger file for tax tracking."
  :type 'file
  :group 'ip-tax)

(defcustom ip-tax-income-account "Income:Freelance"
  "Default Beancount account for freelance income."
  :type 'string
  :group 'ip-tax)

(defcustom ip-tax-expense-account "Expenses:Tax:VAT"
  "Default Beancount account for tax expenses."
  :type 'string
  :group 'ip-tax)

(defcustom ip-tax-asset-account "Assets:Bank:Primary"
  "Default Beancount account for primary bank account."
  :type 'string
  :group 'ip-tax)

(defcustom ip-tax-auto-record-invoices t
  "Automatically record transactions when invoices are finalized."
  :type 'boolean
  :group 'ip-tax)

;;; Internal Functions

(defun ip-tax--ensure-ledger ()
  "Create ledger file if it doesn't exist."
  (let ((ledger-path (expand-file-name ip-tax-ledger-file)))
    (unless (file-exists-p ledger-path)
      (make-directory (file-name-directory ledger-path) t)
      (with-temp-file ledger-path
        (insert ";; Tax Ledger for IP Management System\n")
        (insert ";; Generated by ip-tax.el\n")
        (insert ";; File encoding: UTF-8\n\n")
        (insert (format "option \"operating_currency\" \"EUR\"\n\n"))
        (insert (format "%s open %s\n" (format-time-string "%Y-%m-%d") ip-tax-income-account))
        (insert (format "%s open %s\n" (format-time-string "%Y-%m-%d") ip-tax-expense-account))
        (insert (format "%s open %s\n\n" (format-time-string "%Y-%m-%d") ip-tax-asset-account)))
      (ip-debug-log 'success 'tax "Created ledger file: %s" ledger-path))))

(defun ip-tax--format-amount (amount currency)
  "Format AMOUNT with CURRENCY for Beancount (e.g., '100.00 EUR')."
  (format "%.2f %s" 
          (if (stringp amount) (string-to-number amount) amount) 
          currency))

(defun ip-tax--format-transaction (date description amount currency counter-account)
  "Format a Beancount transaction entry.
AMOUNT is positive for income (credit to asset), negative for expense (debit from asset).
COUNTER-ACCOUNT is the opposite account (Income:* or Expenses:*)."
  (let* ((abs-amount (abs amount))
         (formatted-amount (ip-tax--format-amount abs-amount currency))
         (asset-sign (if (> amount 0) "" "-"))
         (counter-sign (if (> amount 0) "-" ""))
         (asset-line (format "  %-40s %s%s"
                            ip-tax-asset-account
                            asset-sign
                            formatted-amount))
         (counter-line (format "  %-40s %s%s"
                              counter-account
                              counter-sign
                              formatted-amount)))
    (format "%s * \"%s\"\n%s\n%s\n"
            date
            description
            asset-line
            counter-line)))

(defun ip-tax--record-transaction (date description amount currency counter-account)
  "Record a transaction in the Beancount ledger.
AMOUNT: positive for income, negative for expense.
COUNTER-ACCOUNT: the account to debit/credit against the asset account."
  (unless ip-tax-enabled
    (ip-debug-log 'debug 'tax "Tax tracking disabled, skipping transaction")
    (cl-return-from ip-tax--record-transaction nil))

  (ip-tax--ensure-ledger)

  (let ((entry (ip-tax--format-transaction date description amount currency counter-account)))
    (condition-case err
        (progn
          (with-temp-buffer
            (set-buffer-file-coding-system 'utf-8)
            (insert-file-contents ip-tax-ledger-file)
            (goto-char (point-max))
            (unless (bolp) (insert "\n"))
            (insert entry)
            (write-region (point-min) (point-max) ip-tax-ledger-file nil 'silent))
          (ip-debug-log 'success 'tax "Recorded transaction: %s | %s | %.2f %s"
                        date description amount currency)
          t)
      (error
       (ip-debug-log 'error 'tax "Failed to record transaction: %s"
                     (error-message-string err))
       nil))))

;;; Public API

;;;###autoload
(defun ip-tax-record-income (&optional date description amount currency)
  "Record income transaction to ledger.
If called interactively, prompts for all values.
If called programmatically, DATE, DESCRIPTION, AMOUNT, and CURRENCY can be provided."
  (interactive)
  (let ((date (or date (read-string "Date (YYYY-MM-DD): " 
                                    (format-time-string "%Y-%m-%d"))))
        (desc (or description (read-string "Description: ")))
        (amt (or amount (read-number "Amount (positive): ")))
        (curr (or currency (read-string "Currency: " "EUR"))))
    (ip-tax--record-transaction date desc amt curr ip-tax-income-account)))

;;;###autoload
(defun ip-tax-record-expense (&optional date description amount currency)
  "Record expense transaction to ledger.
If called interactively, prompts for all values.
If called programmatically, DATE, DESCRIPTION, AMOUNT, and CURRENCY can be provided."
  (interactive)
  (let ((date (or date (read-string "Date (YYYY-MM-DD): " 
                                    (format-time-string "%Y-%m-%d"))))
        (desc (or description (read-string "Description: ")))
        (amt (or amount (read-number "Amount (positive): ")))
        (curr (or currency (read-string "Currency: " "EUR"))))
    (ip-tax--record-transaction date desc (- amt) curr ip-tax-expense-account)))

;;;###autoload
(defun ip-tax-notify-income (&rest plist)
  "Record income from external source (e.g., ip-invoice).
PLIST should contain :client, :amount, :date, :currency, and :description."
  (let ((client (plist-get plist :client))
        (amount (plist-get plist :amount))
        (date (or (plist-get plist :date) (format-time-string "%Y-%m-%d")))
        (currency (or (plist-get plist :currency) "EUR"))
        (description (or (plist-get plist :description)
                        (format "Income from %s" client))))
    (ip-tax--record-transaction
     date
     description
     (if (stringp amount) (string-to-number amount) amount)
     currency
     ip-tax-income-account)))

;;;###autoload
(defun ip-tax-show-ledger ()
  "Open the tax ledger file for viewing/editing."
  (interactive)
  (ip-tax--ensure-ledger)
  (find-file ip-tax-ledger-file)
  (when (and (featurep 'beancount)
             (fboundp 'beancount-mode))
    (beancount-mode)))

;;;###autoload
(defun ip-tax-validate-ledger ()
  "Validate the Beancount ledger file.
Requires bean-check to be installed and available in PATH."
  (interactive)
  (ip-tax--ensure-ledger)
  (let ((bean-check (executable-find "bean-check")))
    (if bean-check
        (let ((output (shell-command-to-string 
                      (format "%s %s" bean-check ip-tax-ledger-file))))
          (if (string-empty-p output)
              (message "Ledger validation successful")
            (message "Ledger validation errors:\n%s" output)))
      (message "bean-check not found. Install Beancount tools to validate."))))

;;; Integration with ip-invoice

(defun ip-tax--on-invoice-finalized (invoice-data)
  "Hook function to record transaction when invoice is finalized.
INVOICE-DATA is the plist returned by ip-invoice-generate-data."
  (when (and ip-tax-enabled ip-tax-auto-record-invoices)
    (let ((client-id (plist-get (plist-get invoice-data :client) :ID))
          (amount (plist-get invoice-data :total))
          (date (plist-get invoice-data :generated))
          (currency (plist-get invoice-data :currency))
          (invoice-id (plist-get invoice-data :invoice-id)))
      (ip-tax-notify-income 
       :client client-id
       :amount amount
       :date date
       :currency currency
       :description (format "Invoice %s for %s" invoice-id client-id)))))

;; Install advice on ip-invoice-generate if module is loaded
(when (featurep 'ip-invoice)
  (advice-add 'ip-invoice-generate :after
              (lambda (&rest args)
                (when (equal (nth 3 args) 'final)
                  (let ((invoice (apply #'ip-invoice-generate-data (butlast args))))
                    (ip-tax--on-invoice-finalized invoice))))
              '((name . ip-tax-auto-record))))

;;; Setup and Teardown

;;;###autoload
(defun ip-tax-setup ()
  "Initialize tax tracking module."
  (interactive)
  (ip-tax--ensure-ledger)
  (when (featurep 'ip-invoice)
    (advice-add 'ip-invoice-generate :after
                (lambda (&rest args)
                  (when (equal (nth 3 args) 'final)
                    (let ((invoice (apply #'ip-invoice-generate-data (butlast args))))
                      (ip-tax--on-invoice-finalized invoice))))
                '((name . ip-tax-auto-record))))
  (ip-debug-log 'info 'tax "Tax tracking module initialized"))

;;;###autoload
(defun ip-tax-teardown ()
  "Clean up tax tracking module."
  (interactive)
  (advice-remove 'ip-invoice-generate '((name . ip-tax-auto-record)))
  (ip-debug-log 'info 'tax "Tax tracking module deactivated"))

;;; Minor Mode

(defvar ip-tax-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-c t i") 'ip-tax-record-income)
    (define-key map (kbd "C-c t e") 'ip-tax-record-expense)
    (define-key map (kbd "C-c t l") 'ip-tax-show-ledger)
    (define-key map (kbd "C-c t v") 'ip-tax-validate-ledger)
    map)
  "Keymap for `ip-tax-mode'.")

;;;###autoload
(define-minor-mode ip-tax-mode
  "Minor mode for tax tracking integration with IP management system.

\\{ip-tax-mode-map}"
  :lighter " Tax"
  :keymap ip-tax-mode-map
  :group 'ip-tax
  (if ip-tax-mode
      (ip-tax-setup)
    (ip-tax-teardown)))

(provide 'ip-tax)
;;; ip-tax.el ends here